name: Deploy to AWS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ask yining to add values into secret
      - name: Create .env.local for supabase
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          directory: ''
          file_name: .env.local
          fail_on_empty: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and save docker images
        id: save-docker-image
        run: |
          docker build -t ${{ secrets.AWS_REPOSITORY_URI }}/todo:latest .
          docker build -t ${{ secrets.AWS_REPOSITORY_URI }}/todo:${{ github.sha }} .
          docker save ${{ secrets.AWS_REPOSITORY_URI }}/todo:${{ github.sha }} > todo-${{ github.sha }}.tar

      - uses: actions/upload-artifact@v3
        if: ${{ steps.save-docker-image.outcome == 'success' }}
        with:
          name: image-${{ github.sha }}.tar
          path: image-${{ github.sha }}.tar
          retention-days: 5

      - name: Push images into ECR
        run: |
          docker push ${{ secrets.AWS_REPOSITORY_URI }}/todo:${{ github.sha }}
          docker push ${{ secrets.AWS_REPOSITORY_URI }}/todo:latest

      - name: Restart task
        run: aws ecs update-service --force-new-deployment --service todo-service --cluster todo
